/**
 * Canonical domain types — derived field-for-field from BrandPipeline.jsx.
 * The cockpit is the contract: do not rename or add fields here without a
 * matching change in the front end.
 */

/** Channel ids — from CHANNELS in the cockpit. */
export type ChannelId = "blog" | "instagram" | "x" | "email" | "tiktok";

/** Image provider — from the onboarding "Image model" segmented control. */
export type ImageModel = "gpt-image-2" | "nano-banana";

/** Run cadence — from the onboarding "Run cadence" control. */
export type Cadence = "manual" | "daily" | "weekly";

/** Publish target — from the onboarding "Publish target" control. */
export type PublishTarget = "draft" | "blotato" | "cms";

/** Terminal outcome of a run — from the cockpit outcome card / run history. */
export type RunOutcome = "published" | "rejected";

/**
 * Pipeline stages, in order. Matches STAGES in the cockpit exactly.
 * `gate` produces the draft and pauses for human approval before `publish`.
 */
export type StageId = "measure" | "seo" | "brief" | "create" | "gate" | "publish";

/**
 * Per-stage status. The cockpit renders: queued | running | done | review | rejected
 * ("idle" is a UI-only state when no run exists, never persisted).
 */
export type StageStatus = "queued" | "running" | "done" | "review" | "rejected";

/**
 * Overall run lifecycle status (server-side). The cockpit derives its view
 * from stage statuses + draft presence; these map onto that:
 *  - queued/running drive the animated rail
 *  - awaiting_approval shows the gate card (draft + score)
 *  - published/rejected/errored are terminal
 */
export type RunStatus =
  | "queued"
  | "running"
  | "awaiting_approval"
  | "published"
  | "rejected"
  | "errored";

/** Where to place the composited logo/wordmark on a generated image. */
export type LogoPosition = "bottom-right" | "bottom-center" | "top-left";

/**
 * Brand assets attached at onboarding/edit and used during generation.
 * URLs are app-relative (/api/assets/:id, served from GridFS) or external.
 */
export interface BrandAssets {
  /** Primary logo, composited onto generated creatives. */
  logoUrl?: string | null;
  /** Optional separate wordmark (text logo). */
  wordmarkUrl?: string | null;
  /** Where the logo is overlaid on images. */
  logoPosition?: LogoPosition;
  /** Hex brand colours, fed into image prompts. */
  palette?: string[];
  /** Reference images for on-brand / consistent-character generation. */
  referenceImageUrls?: string[];
}

/** A single measured query/term with whatever the source provides. */
export interface MetricItem {
  term: string;
  clicks?: number;
  impressions?: number;
  ctr?: number;
  position?: number;
  engagement?: number;
}

/**
 * KPI snapshot produced by the measure stage and fed back into seo/brief —
 * this is what "closes the loop": each cycle leans into what performed and
 * refreshes what didn't.
 */
export interface BrandKpis {
  updatedAt: string;
  /** Which metric providers contributed (e.g. "internal-history", "gsc"). */
  sources: string[];
  /** Keywords/topics to lean into next cycle. */
  doubleDown: string[];
  /** Topics to refresh or stop repeating. */
  refresh: string[];
  /** Top measured queries (when an external source is wired). */
  topQueries: MetricItem[];
  /** One-paragraph agent-readable insight. */
  summary: string;
}

/** Where the post-publish funnel (landing + emails) gets sent. */
export type FunnelProvider = "store" | "webhook" | "kartra";

/** Per-brand funnel config (set in the cockpit). */
export interface FunnelConfig {
  enabled?: boolean;
  provider?: FunnelProvider;
}

/** Landing page copy generated by the funnel step. */
export interface LandingPage {
  headline: string;
  subhead: string;
  sections: { heading: string; body: string }[];
  cta: string;
}

/** One email in the generated nurture sequence. */
export interface FunnelEmail {
  subject: string;
  body: string;
}

/** Funnel output persisted on a run after publish. */
export interface FunnelOutput {
  landingPage: LandingPage;
  emails: FunnelEmail[];
  /** Where it was sent (e.g. "stored", "webhook", "Kartra"). */
  pushedTo: string | null;
}

/** Draft produced at the gate — shape matches run.draft in the cockpit. */
export interface Draft {
  title: string;
  meta: string;
  body: string;
  keywords: string[];
  score: number;
  /** Generated creative (hosted or data URL); shown in the gate card. */
  imageUrl?: string | null;
}

/** A single stage's live status within a run, for the cockpit rail. */
export interface RunStage {
  id: StageId;
  status: StageStatus;
}

/**
 * Brand — exactly the cockpit's brand fields (seedBrand / onboarding draft).
 * `id` is a slug; `runs` is a denormalized history list the dashboard reads.
 */
export interface Brand {
  id: string;
  name: string;
  audience: string;
  positioning: string;
  voice: string;
  dos: string;
  nevers: string;
  channels: ChannelId[];
  keywords: string[];
  imageModel: ImageModel;
  cadence: Cadence;
  publishTarget: PublishTarget;
  gateThreshold: number;
  /**
   * Long-form brand DNA (the brand-dna.md equivalent) injected into every
   * agent's prompt — richer brand context beyond voice/dos/nevers.
   */
  brandDna?: string;
  /** Logo / visual references used during asset generation. */
  assets?: BrandAssets;
  /** Brand site (used by the GSC metrics provider to match pages/queries). */
  siteUrl?: string;
  /** Latest KPI snapshot from the measure stage (server-owned, closes the loop). */
  kpis?: BrandKpis;
  /** Post-publish funnel (landing page + email sequence) config. */
  funnel?: FunnelConfig;
  /**
   * Blotato connected-account ids, keyed by Blotato platform
   * (tiktok | instagram | twitter | facebook). Server-side config, not shown
   * in the cockpit. Used by the publish stage when publishTarget === "blotato".
   */
  blotatoAccounts?: Record<string, string>;
  /** Lightweight run summaries for the dashboard / history card. */
  runs: RunSummary[];
  createdAt?: string;
  updatedAt?: string;
}

/** Run summary as embedded in brand.runs — matches the cockpit history rows. */
export interface RunSummary {
  id: string;
  /** Epoch millis, as the cockpit uses (relTime expects ms). */
  at: number;
  outcome: RunOutcome;
  title: string;
}

/** Full run document the cockpit polls via GET /api/runs/:id. */
export interface Run {
  id: string;
  brandId: string;
  status: RunStatus;
  stages: RunStage[];
  draft: Draft | null;
  outcome: RunOutcome | null;
  costUsd: number | null;
  /** Funnel collateral generated after publish (landing + emails). */
  funnel?: FunnelOutput | null;
  createdAt: string;
  updatedAt: string;
}

/** Stage order + display metadata, mirrored from STAGES in the cockpit. */
export const STAGES: ReadonlyArray<{ id: StageId; label: string }> = [
  { id: "measure", label: "Measure" },
  { id: "seo", label: "Analyze & keywords" },
  { id: "brief", label: "Brief + brand voice" },
  { id: "create", label: "Create copy + creative" },
  { id: "gate", label: "Brand-voice gate" },
  { id: "publish", label: "Publish" },
];

/** Just the ordered ids, the worker's source of truth for progression. */
export const STAGE_IDS: StageId[] = STAGES.map((s) => s.id);
